name: git-pr-release
description: Create a pull request to release changes from a staging branch to a production branch.
inputs:
  staging_branch:
    description: 'The staging branch to create PR from'
    required: true
  production_branch:
    description: 'The production branch to create PR to'
    required: true
  environment_label:
    description: 'The environment label for the PR'
    required: false
    default: ''
  token:
    description: 'GitHub token for authentication'
    required: true

runs:
  using: composite
  steps:
    - run: git-pr-release --squashed
      shell: bash
      env:
        TZ: Asia/Tokyo
        GIT_PR_RELEASE_TOKEN: ${{ inputs.token }}
        GIT_PR_RELEASE_BRANCH_PRODUCTION: ${{ inputs.production_branch }}
        GIT_PR_RELEASE_BRANCH_STAGING: ${{ inputs.staging_branch }}
        GIT_PR_RELEASE_LABELS: ${{ inputs.environment_label }}
        GIT_PR_RELEASE_TEMPLATE: .github/pr-release-template.erb
